version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visitCountSAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-158k90nh9lrop"
s3_prefix = "visitCountSAM"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
